
CREATE WAREHOUSE RETAIL_WH
WITH WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
COMMENT = 'Warehouse for Retail Analytics Pipeline';

CREATE DATABASE RETAIL_DB;

USE DATABASE RETAIL_DB;
USE WAREHOUSE RETAIL_WH;

CREATE SCHEMA RAW;
CREATE SCHEMA TRANSFORMED;
CREATE SCHEMA ANALYTICS;

USE SCHEMA RAW;

CREATE TABLE RAW_SALES (
    INVOICENO       VARCHAR(20),
    STOCKCODE       VARCHAR(20),
    DESCRIPTION     VARCHAR(255),
    QUANTITY        NUMBER(10,2),
    INVOICEDATE     VARCHAR(30),
    UNITPRICE       NUMBER(10,2),
    CUSTOMERID      VARCHAR(20),
    COUNTRY         VARCHAR(100)
);

CREATE STAGE RETAIL_STAGE
COMMENT = 'Stage for loading retail CSV files';

CREATE FILE FORMAT RETAIL_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE;

SHOW FILE FORMATS IN SCHEMA RAW;
SHOW STAGES IN SCHEMA RAW;
SHOW TABLES IN SCHEMA RAW;

USE DATABASE RETAIL_DB;
USE SCHEMA RAW;
USE WAREHOUSE RETAIL_WH;


COPY INTO RAW_SALES
FROM @RETAIL_STAGE/online_retail.csv
FILE_FORMAT = RETAIL_CSV_FORMAT
ON_ERROR = 'CONTINUE';

